%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PROJETO: CPVT3N - Modelagem no concentrador fotovoltaico/térmico 
%          considerando reservatório estratificado em 3 níveis
% ARQUIVO: Código estratificação do reservatorio
% NOME: LETÍCIA FRITZ HENRIQUE
% E-mail: leticiafritz@id.uff.br
% ULTIMA REVISÃO: 27/07/2021
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 
function RESERVATORIO = getEstratificacao(RESERVATORIO,massaNivel,...
    mpontoc,Ts,perda,minuto)

    %% Reservatorio foi todo utilizado
    if (massaNivel(1,4)>0)
        RESERVATORIO.Tagua(minuto+1,1)  = RESERVATORIO.TL+perda(minuto,1);
        RESERVATORIO.Tagua(minuto+1,2)  = RESERVATORIO.TL+perda(minuto,2);
        RESERVATORIO.Tagua(minuto+1,3)  = RESERVATORIO.TL+perda(minuto,3);
    %% Reservatorio não foi utilizado
    elseif (mpontoc == 0)
        RESERVATORIO.Tagua(minuto+1,1) = RESERVATORIO.Tagua(minuto,1)+...
            perda(minuto,1);
        RESERVATORIO.Tagua(minuto+1,2) = RESERVATORIO.Tagua(minuto,2)+...
            perda(minuto,2);
        RESERVATORIO.Tagua(minuto+1,3) = RESERVATORIO.Tagua(minuto,3)+...
            perda(minuto,3);
    %% Reservatório foi utilizado
    else
        RESERVATORIO.Tagua(minuto+1,1) = RESERVATORIO.Tagua(minuto,1);
        RESERVATORIO.Tagua(minuto+1,2) = RESERVATORIO.Tagua(minuto,2);
        RESERVATORIO.Tagua(minuto+1,3) = RESERVATORIO.Tagua(minuto,3);
        % Correção devido ao termostato
        if massaNivel(1,1)>0
            if RESERVATORIO.Res(1,1) == 1 && massaNivel(1,1) > 0
                RESERVATORIO.Tagua(minuto+1,1) = RESERVATORIO.Termostato;
            end
        end
        % Nova temperatura do Nível 1
        Ts1  = perda(minuto,1)+...
            (RESERVATORIO.massa(1,1)*RESERVATORIO.Tagua(minuto+1,1)+...
            RESERVATORIO.Fc(1,1)*mpontoc*Ts(minuto,1)-...
            RESERVATORIO.Fc(1,1)*mpontoc*RESERVATORIO.Tagua(minuto+1,1)+...
            (RESERVATORIO.FL(2,1)+RESERVATORIO.FL(3,1))*massaNivel(1,1)*...
            RESERVATORIO.Tagua(minuto+1,2)+...
            RESERVATORIO.FL(1,1)*massaNivel(1,1)*RESERVATORIO.TL-...
            massaNivel(1,1)*RESERVATORIO.Tagua(minuto+1,1))/...
            RESERVATORIO.massa(1,1);
        % Nova temperatura do Nível 2
        Ts2 =  perda(minuto,2)+...
            (RESERVATORIO.massa(2,1)*RESERVATORIO.Tagua(minuto+1,2)+...
            RESERVATORIO.Fc(2,1)*mpontoc*Ts(minuto,1)+...
            RESERVATORIO.Fc(1,1)*mpontoc*Ts1-...
            (RESERVATORIO.Fc(1,1)+RESERVATORIO.Fc(2,1))*mpontoc*...
            RESERVATORIO.Tagua(minuto+1,2)+...
            RESERVATORIO.FL(3,1)*massaNivel(1,1)*...
            RESERVATORIO.Tagua(minuto+1,3)+...
            RESERVATORIO.FL(2,1)*massaNivel(1,1)*RESERVATORIO.TL-...
            (RESERVATORIO.FL(2,1)+RESERVATORIO.FL(3,1))*massaNivel(1,1)*...
            RESERVATORIO.Tagua(minuto+1,2))/RESERVATORIO.massa(2,1);
        % Nova temperatura do Nível 3
        Ts3  = perda(minuto,3)+(RESERVATORIO.massa(3,1)*...
            RESERVATORIO.Tagua(minuto+1,3)+...
            RESERVATORIO.Fc(3,1)*mpontoc*Ts(minuto,1)+...
            (RESERVATORIO.Fc(1,1)+RESERVATORIO.Fc(2,1))*mpontoc*Ts2-...
            mpontoc*RESERVATORIO.Tagua(minuto+1,3)+...
            RESERVATORIO.FL(3,1)*massaNivel(1,1)*RESERVATORIO.TL-...
            RESERVATORIO.FL(3,1)*massaNivel(1,1)*...
            RESERVATORIO.Tagua(minuto+1,3))/RESERVATORIO.massa(3,1);
        massaNivel = massaNivel(1,2:4);
        massaNivel(1,4) = 0;
        RESERVATORIO.Tagua(minuto+1,1) = Ts1;
        RESERVATORIO.Tagua(minuto+1,2) = Ts2;
        RESERVATORIO.Tagua(minuto+1,3) = Ts3;
        % Para atender toda a carga
        while (massaNivel(1,1) > 0)
            % Nova temperatura do Nível 1
            Ts1  = perda(minuto,1)+(RESERVATORIO.massa(1,1)*...
                RESERVATORIO.Tagua(minuto+1,1)+...
                RESERVATORIO.Fc(1,1)*mpontoc*Ts(minuto,1)-...
                RESERVATORIO.Fc(1,1)*mpontoc*...
                RESERVATORIO.Tagua(minuto+1,1)+...
                (RESERVATORIO.FL(2,1)+RESERVATORIO.FL(3,1))*...
                massaNivel(1,1)*RESERVATORIO.Tagua(minuto+1,2)+...
                RESERVATORIO.FL(1,1)*massaNivel(1,1)*RESERVATORIO.TL-...
                massaNivel(1,1)*RESERVATORIO.Tagua(minuto+1,1))/...
                RESERVATORIO.massa(1,1);
            % Nova temperatura do Nível 2
            Ts2  =  perda(minuto,2)+(RESERVATORIO.massa(2,1)*...
                RESERVATORIO.Tagua(minuto+1,2)+...
                RESERVATORIO.Fc(2,1)*mpontoc*Ts(minuto,1)+...
                RESERVATORIO.Fc(1,1)*mpontoc*Ts1-...
                (RESERVATORIO.Fc(1,1)+RESERVATORIO.Fc(2,1))*mpontoc*...
                RESERVATORIO.Tagua(minuto+1,2)+...
                RESERVATORIO.FL(3,1)*massaNivel(1,1)*...
                RESERVATORIO.Tagua(minuto+1,3)+...
                RESERVATORIO.FL(2,1)*massaNivel(1,1)*RESERVATORIO.TL-...
                (RESERVATORIO.FL(2,1)+RESERVATORIO.FL(3,1))*...
                massaNivel(1,1)*RESERVATORIO.Tagua(minuto+1,2))/...
                RESERVATORIO.massa(2,1);
            % Nova temperatura do Nível 3
            Ts3  = perda(minuto,3)+(RESERVATORIO.massa(3,1)*...
                RESERVATORIO.Tagua(minuto+1,3)+...
                RESERVATORIO.Fc(3,1)*mpontoc*Ts(minuto,1)+...
                (RESERVATORIO.Fc(1,1)+RESERVATORIO.Fc(2,1))*mpontoc*Ts2-...
                mpontoc*RESERVATORIO.Tagua(minuto+1,3)+...
                RESERVATORIO.FL(3,1)*massaNivel(1,1)*RESERVATORIO.TL-...
                RESERVATORIO.FL(3,1)*massaNivel(1,1)*...
                RESERVATORIO.Tagua(minuto+1,3))/RESERVATORIO.massa(3,1);        
            massaNivel = massaNivel(1,2:4);
            massaNivel(1,4) = 0;
            RESERVATORIO.Tagua(minuto+1,1) = Ts1;
            RESERVATORIO.Tagua(minuto+1,2) = Ts2;
            RESERVATORIO.Tagua(minuto+1,3) = Ts3;
        end
    end
    
end